epicweb-dev/advanced-react-apis

- src/exercises/01.md
> Typo fix in first exercise doc!

- src/exercises/04.js
Currently you can add pokemon that don't exist! Without checking for Pokemon data we can create non-pokemon buttons that have "Unknown" as data!
> Prevent adding Unknown Pokemon

- src/exercise/03.md
The path to the starting point file for Exercise 03 Extra Credit 2 should be ./src/exercise/03.extra-2.js.
> corrected the starting point for Exercixe 03 Extra Credit 2

- README.md
> docs(readme): added links to socials urls #31

- src/__tests__/03.js
- src/__tests__/05.js
- src/__tests__/06.js
Maybe you renamed the folder but not the paths in the comments?
> Fix typo to be able to run the tests on files in src/exercise

- src/exercise/05.md
Just fixin' up a typo in a sentence in 05.md :)
> Fix grammar typo in 05.md

- src/exercise/06.md
Hi Kent, saw this typo while running through the materials. Hope you don't mind me PR-ing to fix this.
> Fix typo in 06.md

- src/exercise/01.md
- src/final/01.extra-4.js
Hi @kentcdodds!
I just thought it could be a bit nicer if the step prop is used in the reducer through the action.
That way it is a little more compatible with the scenario in previous stages.
Thanks for creating this repo!
> Add the step prop to the action to keep compatibility with previous cases

- src/exercise/02.md
Saw a small error on the md file extra-credit 1 of exercice 2 where instead of
```js
const state = useAsync(asyncCallback)
```
It should be
```js
const state = useAsync(asyncCallback, {
status: pokemonName ? 'pending' : 'idle',
})
```
> Change what we expect to see as a result to the first extra-credit of the exercice 2

- src/exercise/02.js
• Fix `this'll` -> `this will`
> FIx small typo in 02.js

- src/final/02.extra-3.js
also adds in comments about why you would want to use useLayoutEffect for a more general custom hook.
> update the final file for extra credit to match video

- src/exercise/02.js
Switches contraction to possessive pronoun.
Side-note, thanks for the wonderful material :)
> Fix small typo

- README.md
link to JSConf talk Getting Closure on React Hooks by Shawn Wang | JSConf.Asia 2019
> Add additional resoruces sectiont readme includeing first link

- src/exercise/02.md
Fix useEffect in extracredit 2. We don't want to use the run function as a cleanup :)
> Fix useEffect snippet in useCallback: custom hooks extra credit 2.

- src/exercise/05.md
Found this small spelling error while going through the exercise, I thought it could be nice and small first PR 🎉
> Fix spelling in exercise 05

- src/exercise/02.md
I'm not a native English user. Feel free to ignore if this is intended.
> Potential Typo

- src/final/01.extra-4.js
I have a tiny improvement to this particular exercise, since we're using the "redux pattern" and the state is an object I'd propose to spread over the current state inside switch statement. This would make it more consistent with the previous extra examples shown in this particular exercise.
> Improve 01 extra-4 exercise

- src/final/02.extra-3.js
- src/utils.js
The cleanup function should return void not a boolean
> fix(final,utils): useEffect cleanup function

- src/exercise/02.md
Noticed a few misspelled words and thought I'd try to make a pull request for them.
I hope I did the forking and branching correctly.
Thanks,
William
> little spell checking

- src/exercise/02.md
The code in the video was different, so I've updated the mark down to reflect the changes
> Updated code in the extra credit

- src/final/02.extra-1.js
- src/final/02.extra-2.js
- src/final/02.extra-3.js
- src/final/02.js
This results in cleaner diffs between the respective 02 "exercise" and "final" files.
Consistency between starting code and final solution code reduces noise, clarifies which changes are required to solve the 02 exercises.
> Propagate #5557aba refactor to solution files

- src/exercise/02.md
Updating the sentence to make it more concise.
> Update 02.md to remove redundancy of `first`

- src/exercise/02.js
Adding the middle `initialState` argument to the `useAsync` hook signature in the hints. 
I found it a bit surprising when I watched the solution video, because there was nothing hinting towards accepting an initial state. If keeping it out was intentional to make things simpler then feel free to close this PR 🙏🏻 
Thanks for the amazing course!
> add initialState arg to useAsync hook signature

- exercises/04.context/01.problem.provider/index.tsx
> fix: typo in comment

- exercises/02.state-optimization/README.mdx
Fix bug where `setState` does not return a new state.
> fix: typo in `02.state-optimization/README.mdx`

- exercises/01.use-reducer/01.problem.new-state/README.mdx
These two articles were referenced in the intro video:
- https://kentcdodds.com/blog/how-to-implement-usestate-with-usereducer
- https://kentcdodds.com/blog/should-i-usestate-or-usereducer
> Add Article links 01.use-reducer/01.problem.new-state

- exercises/FINISHED.mdx
I think Epic React makes more sense here
> possible correction
