epicweb-dev/advanced-react-apis

- scripts/autofill-feedback-email.js
Tested this and it works locally on Windows 10 with vscode. Would need someone to test the regex on Mac as I don't have one.
I imagine this could be done to the other projects as I remember having this issue in learn-react-hooks as well.
> Email fill script does not work on Windows

- src/exercises/05.js
If the message array length equals 0, the second slice param becomes -1 which refills the messages array up to the first index.
> Clamp remove value to 0

- src/exercises/03.md
`useCount` isn't mentioned anywhere except this line. Dunno if you wanted to make a `useCount` hook as extra credit, but as it is now, this is a bit confusing.
> Remove reference to useCount in 03.md

- README.md
Hey Kent, I noticed the verify script doesn't exist in this repo.
Not sure if that's the right change, if not, just close this one and tweak the readme the way you want :)
> there is no ./scripts/verify in this repo

- src/exercise/05.js
Sorry for all the noise today 😜   It looks like [this commit](https://github.com/zacjones93/advanced-react-hooks/commit/5af5761674497603bb907cf943ae2b99778d2748) was only intended to update exercise 06 but exercise 05 got updated to its final solution with all the inline prompts removed. 
- resets exercise 5 to the actual exercise vs having the solution.
The recorded `useImperativeHandle: Scroll to top/bottom` intro lesson would also confirm that the current state of the exercise is incorrect and needs to be reset. The intro shows the prompts that were removed in the above commit,
Here's a screenshot of the diff from the commit that set the solution as the exercise:
> Reset exercise 05 to not have solution

- src/exercise/06.md
• `devtools` -> `DevTools` (to be more consistent with the other references)
> Fix small typo in 06.md

- src/final/01.extra-2.js
- src/final/01.extra-3.js
Hello! I noticed a small difference between the examples in the markdown file and the final code and I just went and fixed it. There are no notable changes in behavior since `step` has a default value of `1`.
> Use the `step` variable so it matches the examples

- src/__tests__/04.js
The current tests for exercise 4 look prone to false positives compared to the other tests that break as soon as I import the initial version instead of the final version. I failed to achieve that because I had no idea how to let the test code notice the subtle difference between when using the `useLayoutEffect` hook and when using the `useEffect` hook. Nevertheless, the new test will fail while someone is making the transition for the exercise.
> add test for scrolling to the bottom

- src/__tests__/01.js
It might be nice to verify the button actually increases the existing value. If you start to implement the extra credit requirements you might accidentally set the count to "step". Then the test would still be green, it only fails when you try to click the button again…
> test: Make sure to verify the extra credit button behavior

- src/final/01.extra-4.js
Very small "improvement" here, but I thought id't be best if the destructured `type` variable was used for consistency.
> Use `type` variable destructured from `action` object in `0.1extra-4.js`

- src/__tests__/02.extra-3.js
I was working through exercise 2-extra 3, and was having a hard time getting the tests to pass, even though my implementation seemed to work fine in the browser, without throwing an error.
I added a `useState` in `useAsync` to track whether or not the fetch should be considered cancelled, and added a `useEffect` in the component with a cleanup method to call the setter for that state.  The test failed on the last step, and when I replaced the `alfredTip` with a plain `expect(console.error).not.toHaveBeenCalled()` I could see this console error:
expect(jest.fn()).not.toHaveBeenCalled()
Expected number of calls: 0
Received number of calls: 1
1: "Warning: An update to %s inside a test was not wrapped in act(...).·
When testing, code that causes React state updates should be wrapped into …
> Wrap in act() to avoid extraneous console.error

- src/exercise/06.md
This is just a picky correction.
The `setCount` in this examples are adding + 1  and not using the `step` prop that are receiveng.
> Using step prop in useDebugValue examples

- src/__tests__/01.js
The code that looks for "commentLessLines" ends up filtering unintended lines . `Counter.toString()` returns this:
```js
function Counter({
initialCount = 0,
step = 1
}) {
// 🐨 replace React.useState with React.useReducer.
// 💰 React.useReducer(countReducer, initialCount)
const [count, setCount] = React.useReducer(countReducer, initialCount); // 💰 you can write the countReducer function so you don't have to make any
// changes to the next two lines of code! Remember:
// The 1st argument is called "state" - the current value of count
// The 2nd argument is called "newState" - the value passed to setCount
const increment = () => setCount(count + step);
return /*#__PURE__*/(0, _jsxDevRuntime.jsxDEV)("button", {
onClick: increment,
children: count
}, void 0, false, {
fileName: _jsxFileName, …
```
> fix test for useReducer, simpleCounter example

- CONTRIBUTING.md
Includes an updated link to the latest series on how to contribute to open source.
> Updated link to egghead.io on how to contribute to open source. 

- src/final/03.extra-2.js
`pokemonName` should be case insensitive to avoid multiple cache entries for searches like "Charizard", "CHARIZARD", "charizard" etc.
> fix pokemonName case sensitivity

- src/exercise/02.md
The typescript syntax in code blocks were not being highlighted. I checked in Firefox Developer Edition (96.0b6 ) and Google Chrome (Version 96.0.4664.110).
> Fix typescript syntax highlighting

- src/exercise/02.md
The `pre` element wasn't rendering the warning:
Swapping it to a code block fixes the rendering issue:
> Pre not rendering, swapped to code block

- src/exercise/02.md
Fixes a small mistake of word order.
> Fix wording

- src/exercise/06.md
Apologies for the slowness on this one.
Fixes #190
> Add note about useDebugValue in production

- src/__tests__/01.js
Test fails when `useReducer` is imported directly
> fix: 01 requires namespace import

- src/exercise/02.md
While reading this section, the sentence on line 125 read awkwardly to me even as a native speaker. Particularly between the implied pause between "though" and "it". I understand the intent and it might be just me; since it gave me pause, I thought it might be worth addressing.
> documentation: Update verbiage to be more readable

- src/exercise/02.md
Since this project adopted React 18 the safe dispatch extra credit is no longer reproducible. This PR updates the exercise description to inform the reader.
> add deprecation warning to safe-dispatch extra credit

- exercises/03.custom-hooks/README.mdx
I'm still not quite clear on the exact distinction between 🦉 and 📜 but went with 🦉 because the other two bullets that are similar did.
> Add caching talk to 03.custom-hooks intro
